Home page
Therealadetunji/Capstone-Project pull request #1
Opened 2022-07-01 17:39 UTC by Therealadetunji

Home-page done with html, css and javacript
javascript used for the mobile menu

2022-07-01 21:07 UTC, Therealadetunji commented
https://www.loom.com/share/db777c58120b4eeb86e2d0c700551c85

2022-07-01 22:16 UTC, vic778 requested changes
## Hello @Therealadetunji 

Good job so far! I know you have worked hard on making this project.  There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
## Required Changes ♻️

- [x] Kindly check comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-01 22:16 UTC, vic778 commented on About-page/index.html
> +    </section>
- [ ] Kindly for each div of this section must have an icon, title and the paragraph as you can see at the screenshot 
 Your template  
![Screenshot from 2022-07-02 00-54-23](https://user-images.githubusercontent.com/77842237/176971980-12a73d7b-96ed-4b2d-a956-c7f868eed157.png)

Figma template 

![Screenshot from 2022-07-02 00-55-08](https://user-images.githubusercontent.com/77842237/176972044-1d84e66d-5c46-4048-b485-e208fc91044b.png)

2022-07-01 22:16 UTC, vic778 commented on About-page/index.html
> +    </section>
- [ ] Kindly you could have a div that contain all information for a particular speaker then a div that contain the image of the speaker and the background image then i second div that contain the name the `p` that must have the color `rgb(236, 82, 66)`  and the last `p` <br>
like `div class="container"> <div class="image">...</div> <div class="details">...</p></div> </div>`
Your Design
![Screenshot from 2022-07-02 01-13-29](https://user-images.githubusercontent.com/77842237/176973336-20faa621-0a40-4e86-b15f-2dd7e64fe5d5.png)

Figma design

![Screenshot from 2022-07-02 01-13-44](https://user-images.githubusercontent.com/77842237/176973361-8da81eda-f99c-4da9-97af-af494b818f77.png)

2022-07-02 02:51 UTC, roshan-bajgain requested changes
Hi @Therealadetunji, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Professional README file. ✔️
- PR has a good summary. ✔️

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-02 02:51 UTC, roshan-bajgain commented on About-page/index.html
> +    </section>
- [ ] [Optional] You have well implemented the required changes said by the previous reviewer but if you look at the `Behance` design, there is equal padding from all sides. Kindly implement it
### your design
![his](https://user-images.githubusercontent.com/81727988/176983752-58862e2d-0a03-471b-9ffa-c1e1c81d9023.png)
### Behance design

![figam](https://user-images.githubusercontent.com/81727988/176983761-6cb9e3bb-7598-4444-86cc-61a31cce6a11.png)

2022-07-02 02:51 UTC, roshan-bajgain commented on About-page/index.html
> +    </section>
- [ ] Kindly implement the requested by the previous reviewer that should have an image, title, and content. Each article has two columns, the first with the image at the left and the second with the title, subtitle, and description in 3 rows.
### Your design
![youuuu](https://user-images.githubusercontent.com/81727988/176983861-189f5356-fc88-4a5b-b662-baaf16362abd.png)
### Orignal design
![figma](https://user-images.githubusercontent.com/81727988/176983868-f3c89a58-df87-459e-8eef-fa3e0c65ad26.png)

2022-07-02 03:47 UTC, mateo951 approved these changes
Hi @Therealadetunji, 

Well done making the changes requested by the previous reviewer 🚀
In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it 🔥 

### Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2022-07-03 07:06 UTC, merged